name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5.9', '2.7.6' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: |
        bundle exec rspec spec --color --format documentation --order random
    - name: Rubocop
      run: |
        bundle exec rubocop -D
